bluewaysw/pcgeos

CInclude/sound.h
Defined names now match the midi-specification (see https://www.midi.org/specifications/item/gm-level-1-sound-set )
=> fixed chords

CInclude/geos.h, Include/Win32/geos.mk, Include/Win32/tool.mk
This set of changes does not yet include the actual glue changes to make a simple geode build successfuly, but it makes some preparations that I think are "reasonable" to improve compatibility and debuggability.  Only tested on win32 so far.
=> Preparations for making glue compatible with Watcom C

Include/Win32/geos.mk
needed for binary compatibility of builds - still working on glue changes for getting LMem heaps to build correctly, but these compile flags are definitely going to be needed to get structure sizes right.
=> Additional wcc compiler options 

Tools/grev/grev.c
Without this fix, the year 2018 would become the year 19118 in the rev-file...
=> fixed Y2K-problem in Targ_FmtTime

Tools/glue/codeview32.c, Tools/glue/msobj.c, Tools/glue/msobj.h
This was a fairly lengthy debugging process, but I fixed the glue linker and cleared up the formatting to make it much clearer on what's going on; the short version is that Watcom uses a different OBJ header to denote publicly reachable local symbols (_near) calls.
These symbols are real, and are "public" in terms of the module. I don't know the GEO file format well enough to know if this is going to be a problem as they may be exposed in ansic.geo despite being near symbols but this would have been an issue with the Borland compiler as well.
=> Fix glue to handle local procedures

Library/Breadbox/Html4Par/htmlpars/htmlpars.goc, Tools/pmake/pmake/parse.c
When trying to set up the repo on a new machine and building according to the instructions, I bumped into this error for the initial "wmake install" step to create pmake.exe.
I used the latest Watcom nightly, and ran the build under Windows 10 64-bit.
=> Fixing typo causing 'wmake install' to fail for initial pmake build

README.md
I have also updated the pointer to the WATCOM package to use the same version as in the travis script.
=> Add instructions for launching target to readme file

.gitignore, README.md, bin/basebox.conf, bin/target.cmd
The basic settings of the target environment in the basebox.conf are not optimal for more powerful systems. Especially the values for cycles and frameskip can often be adjusted. 
The idea is that the user (programmer) can adjust the BaseBox settings without changing the basebox.conf file. To do this, a second conf file (user.conf) is used, which is not included in the repository (see .gitignore). Settings in this file overwrite the corresponding settings in basebox.conf. There is no problem if the user.conf file does not exist.
=> User.conf added to bin/target.cmd and related updates

README.md
I have added some entry points to the techdocs from the top-level Readme, so they become more visible, and perhaps also available for web crawling, so searches for technical GEOS terms can turn up more results.
=> Making techdocs more accessible

CInclude/geos.mk, Include/Win32/geos.mk, Include/sun.geos.mk, TechDocs/Markdown/Tools/ttools.md, TechDocs/ascii/Tools/ttools.txt, TechDocs/html/Tools/Tools/TTools_7.htm, Tools/goc/goc.c, Tools/grev/grev.c
This PR resolves issue #188 (ref files are not updated) by adding the -s flag to grev calls in the geos.mk files.
Since grev must also be executed directly on the command line (e.g. new and newrev commands) the following changes have been made:
- Output of a short instruction if there is a problem
- Warning if the change is not saved
- Detailed instructions with the new command "help"
- Update of the outdated documentation
=> Fix #188 (updating rev file), grev tool and realated docs updated.

CInclude/jmorecfg.h, Library/Breadbox/Ijgjpeg/local.mk, Library/Breadbox/ImpGraph/ASMIMP/impgif.asm, Library/Impex/Main/mainC.asm
- forces _pascal conventions for callback (it is not the default for the WATCOM based tool chain)
- made callback assignment WATCOM compatible
- for ds loading at library entry
- fix 2 C stubs (keeping si unchanged [real bugs unrelated to jpeg library])
=> Fixed jpeg library build and integration issues #250

README.md, TechDocs/Markdown/Concepts/cbuild.md, TechDocs/Markdown/Concepts/cclipb.md, TechDocs/Markdown/Concepts/cfile.md, TechDocs/Markdown/Concepts/cgeom.md, TechDocs/Markdown/Concepts/cgraph.md, TechDocs/Markdown/Concepts/cinput.md, TechDocs/Markdown/Concepts/cintro.md, TechDocs/Markdown/Concepts/cuiover.md, TechDocs/Markdown/Concepts/cvm.md, TechDocs/Markdown/Ddk/ddkpcmcia.md, TechDocs/Markdown/Objects/ovis.md, TechDocs/Markdown/Tutorial/Data_Structures_and_UI.md, TechDocs/Markdown/Tutorial/Documents_and_Displays.md, TechDocs/Markdown/Tutorial/Introduction.md, TechDocs/Markdown/Tutorial/Setting_Up.md, TechDocs/Markdown/Tutorial/The_Plan.md, TechDocs/Markdown/Tutorial/The_Primary_Window.md, TechDocs/Markdown/Tutorial/Troubleshooting_Communications.md, TechDocs/Markdown/Tutorial/Views_and_Visual_Objects.md
...after running a link checker on the documentation site.
Also changes the main README.md to point to the deployed version of the documentation.
=> Fixing some small typos in SDK docs

Installed/Appl/Charm/Makefile
Character Map was not built because the Makefile did not reflect the renamed lowercase file names.
=> Missing Makefile to build Charcter Map.

Installed/Appl/Icon/dependencies.mk
One-liner so `pmake` in Install/Appl/Icon will successfully build icon.geo.
=> Fix absolute path in Appl/Icon dependencies.mk

Tools/geodump/geodis.c, Tools/geodump/geodump.c, Tools/glue/msobj.c, Tools/glue/obj.c, Tools/glue/pass2ms.c
This patch should resolve the issues that we have occasionally seen when build `bbxbrow.geo` (#120). There are actually two separate issues that caused build failures through memory overwrites:
- An uninitialized variable because of a wrong order of function calls (this is the main cause of #120).
- A less common bug that results from inconsistent calculation of relocations between pass1 and pass2 in glue: what happens is that glue tries to predict the number of relocations in each segment in pass 1 and then builds the actual relocations in pass 2, sometimes adjusting the count. However, with Watcom this fails for the special case of the pseudo-symbols created for "protominor" versions in libraries. These are predicted as function pointers with 1 combined relocation for segment+offset, …
=> Fix spurious glue failures when building browser

Appl/Breadbox/BBGrmt/RBOXUI.goc
Gourmet Textzeile abgeschnitten. #413
LÖSUNG :
GrSetClipRect(gstate, PCT_REPLACE,
0,                     /* left */
0,      /* top */
(6.5 * 72),                 /* right */
(9 * 72));   /* bottom */  
Die -6 entfernt und es getestet mit Druck in PS Datei.
=> Gourmet Textzeile abgeschnitten. #413

Appl/Breadbox/BBGrmt/RBOXUI.goc
Gourmet updated RBOXUI.goc addded  -7 tested print to PS file , was before double print of the last line in the new side if reciept was longer than 1 side.
In PR before i have just entered TEST in receipt so i could not see this error.
=> Gourmet updated.

Appl/SysTray/SClock/sclock.asm, Appl/SysTray/SClock/sclock.ui, Appl/SysTray/SClock/sclockConstant.def
Improve the SysTray Clock Menu by removing the "Exit Trigger" and adding a Calendar launch trigger that shows the current date.
=> Systray Clock improvements

Driver/Socket/PPP/fsm.goc
With this fix, connecting via PPP works again (tested with a local pppd in the WSL).
What happened was that the Watcom build effectively ifdef'd out the call to advance the state machine for the current protocol, leading to all PPP protocols (especially LCP) getting stuck in "initial" state.
=> Fix inability to connect with PPP in Watcom build

Include/Win32/geode.mk, Tools/scripts/perl/copy-if-different
The updating of ldf files often failed, if there was already an existing copy:
The reason is that the code of `copy-if-different` just never worked correctly and failed to get the sizes of the files. So, if the new file was larger than the old one, the tool would run into a read error and fail (and this failure was ignored in the `geode.mk` makefile to make the build run through, but potentially incorrect library imports and published functions).
=> Fix copy-if-different

Tools/build/product/bbxensem/Template/geos.ini
The extended keyboard is the standard keyboard used today and contains 102 keys. The currently activated keyboard layout does not contain some keys or contains them at the wrong position. For example # and ^.
=> GEOS.INI: 'German keyboard' replaced by 'German extended keyboard'

Library/Breadbox/Treplib/trepcode.goc
This PR fixes  Outliner crash if choose printpreview. #597
=> Fix calls to RT_CHILD and LOCAL_CHILD macros in Treplib library

Appl/IDialup/IDInfo.goc, Appl/PDFViewer/main/gfx.goc, Appl/PDFViewer/main/stream.goc, Appl/SafBuild/safbuildDoc.goc, Appl/SafBuild/safbuildQuestion.goc, Appl/SafBuild/safbuildQuiz.goc, Appl/SafBuild/safbuildVerify.goc, Appl/Safari2/safari2App.goc, Appl/Safari2/safari2File.goc, Appl/Safari2/safari2Game.goc, Appl/Safari2/safari2Timer.goc, Library/FlatFile/Database/ffDatabase.goc, Library/FlatFile/Database/ffDatabaseCreate.goc, Library/FlatFile/Database/ffDatabaseFieldOrder.goc, Library/FlatFile/Database/ffDatabaseImpex.goc, Library/FlatFile/Database/ffDatabaseLayout.goc, Library/FlatFile/Database/ffDatabaseMeta.goc, Library/FlatFile/Database/ffDatabaseParse.goc, Library/FlatFile/Database/ffDatabaseSort.goc, Library/FlatFile/Database/ffDatabaseSubset.goc, Library/FlatFile/FieldProperties/ffFieldProperties.goc
This fixes an issue I came across when looking at #438: some of our code still contains only the old, Borland-style code segment pragmas, so that splitting source files into multiple resources (to keep them below 10k) does not work everywhere. The streams code in the PDFViewer was the most severe case (>40k), but there are some other places as well.
I have not yet fixed this for the browser, HTML impex lib and mail app, as these are probably most useful on the _149-host-tcpip-socket-driver_ branch anyway at the moment. So I will fix them there first and wait for the merge of the internet connectivity to master.
This PR also fixes a small issue with flags on a memory allocation in GeoFile that I saw when smoketesting.
=> Fix code segment pragmas in some apps

Tools/goc/output.c, Tools/utils/printf.c
Fixes #611.
This fix deals with the weird way how _goc_ (and possibly other tools) apply the LF -> CR LF transformation of line endings in Windows. Rather than relying on opening the input and output files in "text" mode (which lets the compiler's runtime library take care of the translation), files are opened in binary mode, and any translation happens explicitly in the code:
- Some CR characters (\r) are removed explicitly in the input parser
- The custom `fprintf()` implementation translates \r to \r\n in formatting strings, when writing to a stream in binary mode
- The custom `sprintf()` implementation translates \r to \r\n in formatting strings all the time (this is what was broken in #611, because it seems to have relied on a weird combination of misinterpreting memory accessed …
=> Tools: perform conversion of \n to \r\n line endings on Windows also in sprintf()

Tools/build/product/bbxensem/Template/geos.ini
Keyword launchLevel was typed wrong as launchLevle
=> Typing Error in geos.ini Section [uiFeatures] "launchLevle" fixed

Driver/Font/TrueType/Adapter/ttadapter.h, Driver/Font/TrueType/Adapter/ttinit.c, Driver/Font/TrueType/Adapter/ttwidths.c
Fixing kerning support of the ttf driver:
- To keep the number of kerning pairs low, only kerning pairs with a kerning value of at least 1% of the units per EM are registered.
- Calculation of size of FontBuf corrected.
fixes #622
=> Performance of fonts with kerning table imporved.

Library/Breadbox/Html4Par/htmlpars/htmlpars.goc
This should fix ISO Latin pages showing "?" for non-ASCII characters after merging the initial UTF-8 support.
Additionally, I noticed and fixed an issue where a DBCS error was triggered by a script containing a Unicode character above 256 (only for EC builds). I saw this on www.bild.de.
=> Browser: default to ISO encoding again, avoid DBCS error in EC

Library/Breadbox/Html4Par/htmlpars/htmlpars.goc, Library/Breadbox/Html4Par/htmlsty.goh
This makes two small changes to the formatting of numbered lists:
- Make the list numbering (or bullet) uses the same style as the rest of the list
- Increased the hanging indent a little bit to leave room for numbers greater than 9
The first change is based on an idea by @HubertHuckevoll. Unlike the proposal in c452039a08ef03dcb3444add3c012bddb74e7220 I have eventually used `currentCS` (the style for the text that is about to be written) rather than `insertParagraphCS` (the style for the pending paragraph just before the list item), because otherwise the first item of a list may be styled incorrectly.
=> Browser list adjustments

Driver/Font/TrueType/Adapter/ttadapter.h
Use a limit that is significant and still keeps the kern table size so that PC/GEOS can deal with it.
=> Adjust kerning value treshold #764

Driver/Font/TrueType/Adapter/ttadapter.h, Driver/Font/TrueType/Adapter/ttcharmapper.c, Driver/Font/TrueType/Adapter/ttinit.c, Driver/Font/TrueType/Adapter/ttwidths.c, Driver/Font/TrueType/FreeType/ft_conf.h, Driver/Font/TrueType/FreeType/ttapi.c, Driver/Font/TrueType/FreeType/ttcmap.c, Driver/Font/TrueType/FreeType/ttinterp.c, Driver/Font/TrueType/Main/ansic_runtime.asm, Driver/Font/TrueType/truetype.gp
This also makes the option not using a large switch command in the interpreter built and run.
2 strategies has been implemented to prevent inter-resource calls:
- Move function that loop over TTF details function (per character for instance) into the segment of the actual data access function
- move often used function from different code resources into fixed memory
This fixes #708.
=> Shuffling segments to prevent intern-resource calling #708

Driver/Font/TrueType/Adapter/ttchars.c, Driver/Font/TrueType/Main/truetypeMetrics.asm, Library/Kernel/Graphics/graphicsFont.asm
Fix metrics stack allocation in ttf driver
make region buffer fit for 'W'
=> Prevent GrCharMetrics to prevent font mapping #843

.github/workflows/pages.yml
see https://github.blog/changelog/2024-12-05-deprecation-notice-github-pages-actions-to-require-artifacts-actions-v4-on-github-com/
=> Update pages.yml: replace deprecated actions/deploy-pages@v2

Driver/Font/TrueType/Adapter/ttmetrics.c, Driver/Font/TrueType/Adapter/ttmetrics.h, Driver/Font/TrueType/Main/truetypeMetrics.asm
- TrueTypeCharMetrics now returns the character in al (like NimbusCharMetrics)
fixes #891
=> ttf driver: fixing metrics
