CInclude/gstring.h
Shouldn't the WinClipPath remain a WinClipPath?!
=> Illegal mix of Doc and Win

README.md
=> changed it's to its, since 'its' is the possessive.

Library/AnsiC/stdio.c, Library/AnsiC/string.c, Tools/pmake/makedpnd/makedpnd.c
Let's try this again. This branch has two fixes, one that corrects casts in AnsiC instead of changing header files, and a fix to makedpnd to allow it to work on Windows due to an errant break statement.
=> Small fixes

Installed/Library/Chart/Makefile, Installed/Library/Chart/dependencies.mk, Installed/Library/IDialC/Makefile, Installed/Library/IDialC/dependencies.mk, Installed/Library/Mailbox/Makefile, Installed/Library/Mailbox/dependencies.mk, Installed/Library/Pen/Makefile, Installed/Library/Pen/dependencies.mk, Installed/Library/Saver/Makefile, Installed/Library/Saver/dependencies.mk, Installed/Library/Socket/Makefile, Installed/Library/Socket/dependencies.mk, Installed/Library/Trans/Database/CSV/Makefile, Installed/Library/Trans/Database/CSV/dependencies.mk, Installed/Library/Trans/SSheet/Lotus123/Makefile, Installed/Library/Trans/SSheet/Lotus123/dependencies.mk
Signed-off-by: Michael Casadevall <michael@casadevall.pro>
=> Refresh makefiles allowing more modules to build

Tools/glue/codeview32.c
=> CV32: fix redefiniton of nameless enums that are encountered multiple

Installed/Tools/Makefile, Installed/Tools/compat/Makefile, Installed/Tools/esp/Makefile, Installed/Tools/uic/Makefile, Tools/pmake/lib/sprite/Makefile
With this PR most building tools are buildable under Linux.
With rev.c28ed40 pmake is buildable under Linux hosts too.
=> Make PC/Geos toolchain buildable under Linux host

TechDocs/Markdown/Tools/tconfig.md, TechDocs/Markdown/Tools/tdebug.md, TechDocs/Markdown/Tools/tswatcm.md, TechDocs/Markdown/Tools/tswta_i.md, TechDocs/Markdown/Tools/tswtj_z.md, TechDocs/Markdown/Tools/ttcl.md, TechDocs/Markdown/Tools/twelcome.md, TechDocs/Markdown/tools.md
Updated the TOC for the added files, changed earlier files for consistency, and added the first file for the Swat Reference Chapter
=> Updates to the Tools Book

Appl/Breadbox/testapps/typetest/type_test_function.c, Appl/Breadbox/testapps/typetest/type_test_function.h, Appl/Breadbox/testapps/typetest/typetest.goc, Appl/Breadbox/testapps/typetest/typetest.gp, Installed/Appl/Breadbox/testapps/typetest/Makefile, Installed/Appl/Breadbox/testapps/typetest/dependencies.mk, Tools/glue/codeview32.c, Tools/glue/codeview32.h
-support for float type added
-test app added
=> support for float type in glue

Appl/Breadbox/testapps/wccrtl/wcc_test_function.c, Appl/Breadbox/testapps/wccrtl/wcc_test_function.h, Appl/Breadbox/testapps/wccrtl/wccrtl.goc, Library/AnsiC/wcc_rtl.asm
Implementation of the missing wcc runtime functions in 386 asm instructions.
=> implementation of the missing runtime functions

Installed/Library/Compress/Makefile, Installed/Library/Compress/dependencies.mk, Library/Compress/compress.gp, Library/Compress/compressConstant.def, Library/Compress/compressMain.asm, Library/Compress/explode.c, Library/Compress/implode.c, Library/Compress/pklib.h, Library/Compress/readme.txt
This integrates the StormLib based reimplementation of the algorithm of PKWARE used in the library.
=> 128 compress lib reimpl

Appl/SDK_C/IrFaxMod/irfaxmod.goc, Appl/SDK_C/IrFaxMod/irfaxmod.gp, Appl/SDK_C/PDA/FloatKbd/floatkbd.gp, Appl/SDK_C/Serial/serial.gp, Appl/SDK_C/Serial2/serial2.goc, Appl/SDK_C/Serial2/serial2.gp, Appl/SDK_C/Talk/talk.goc, Appl/SDK_C/Talk/talk.gp, Appl/SDK_C/no_go/Talk/talk.gp
All these examples can be compiled and executed, but could not be tested extensively because the necessary hardware is missing.
=> Examples Part 3

CInclude/fontID.h, Driver/Font/TrueType/Adapter/ttinit.c, Driver/Font/TrueType/Adapter/ttinit.h, Driver/Font/TrueType/Adapter/ttpath.c
- better algorithm for generating FontID implemented
- crash when printing to postscript fixed
=> 290 ttfdriver rework algorithm for creating font #290 #300

Appl/Breadbox/Hinv10/I2MTHDS.goc
Forgot to remove MemLock( OptrToHandle....  !!
=> Correction

Appl/Breadbox/BBGrmt/RBOXUI.goc
Missing chunk in RBOXUI.goc file.
=> Missing chunk.

Appl/Charm/Text.goc, Appl/Charm/charm.rev
=> CMGetCopyTextPointSize fixed

Appl/Games/Taipei/taipei.ui
.. as requested from Klaus :-)
=> Add ViewControl to Taipei game

Appl/EduApps/Ttype/externs.goh, Appl/EduApps/Ttype/local.mk, Appl/EduApps/Ttype/ttresult.goc, Appl/EduApps/Ttype/ttui.goc, Appl/EduApps/Ttype/ttype.gp, Installed/Appl/EduApps/Ttype/Makefile, Installed/Appl/EduApps/Ttype/dependencies.mk, Installed/Makefile
- Resource names in gp file updated
- work around for a glue issue
- fix some compiler warnings
=> Made Typing Tutor compiling and running

Library/User/User/userUtils.asm
Change the used "Instrument" and reduce volume to make the Key-Click-Sound sound better
=> Edit userUtils.asm for a much prettier Click-Sound

Installed/Appl/NTaker/Makefile, Installed/Appl/NTaker/dependencies.mk
=> Dependency files for NTaker

Driver/Font/TrueType/Adapter/ttadapter.h, Driver/Font/TrueType/Adapter/ttpath.c
=> 603 ttf driver printing in ps file incorrect with some fonts

README.md
=> Change link  in README.md from slack to Discord

Driver/Font/TrueType/Adapter/ttadapter.h, Driver/Font/TrueType/Adapter/ttchars.c, Driver/Font/TrueType/Adapter/ttinit.c, Driver/Font/TrueType/Adapter/ttwidths.c, Driver/Font/TrueType/FreeType/ttcalc.c
- rendering of underscore and minus fixed
- rendering of rotated text areas fixed
=> Ttf driver transformation matrix

Driver/Font/TrueType/Adapter/ttpath.c, Driver/Font/TrueType/Adapter/ttwidths.c
- skew transformation for ttf rendered texts fixed
- supscript- and superscript position for ttf rendered texts fixed
- rendering paths without window handle fixed
fixes #273
=> Ttf driver fixes

Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error1.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error10.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error11.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error12.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error13.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error14.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error15.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error16.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error18.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error19.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error2.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error20.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error3.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error4.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error5.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error6.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error7.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error8.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error9.htm, Tools/build/product/bbxensem/bbxensem.filetree
Added german Htmlerror files from Ensemble 4.1.3 german Patch.
Updated bbxensem.filetree.
Johannes meint er hätte die übersetzt.
=> Htmlerr German

Appl/Games/GeoLadder/Main/sndwork.goc
Don't lock / unlock music data and then use the optr from the ChunkArray. Instead keep locking only the music data ChunkArray. Fixes playing music, so let it be re-enabled.
=> Fixed locking music data / part. Re-enable music again.

Driver/Font/TrueType/Adapter/ttchars.c, Driver/Font/TrueType/FreeType/ttraster.c
- the space is rendered correctly in a region
- German umlauts no longer disappear at certain point sizes
- Algorithm for estimating the size of the render pool improved
fixes #745
=> ttf driver improvements

Driver/Font/TrueType/FreeType/ft_conf.h, Driver/Font/TrueType/FreeType/ttcalc.c, Driver/Font/TrueType/FreeType/ttinterp.c, Driver/Font/TrueType/FreeType/ttobjs.h, Driver/Font/TrueType/FreeType/ttraster.c
- problem with the allocation of the renderpool cache fixed
- some minor optimizations to the bytecode interpreter
=> ttf-driver: fixes and optimizations

Library/Text/UI/uiFont.asm, Library/Text/UI/uiFont.ui
=> Consider font mapping for font controller #795

Library/Spell/IH/ihCalls.asm
=> Fixing spall crash with hyphenation. #800

Library/Pref/ConfigUI/configui.asm, Library/Pref/ConfigUI/configui.def, Library/Pref/ConfigUI/configuiAppearance.ui, Tools/build/product/bbxensem/Template/geos.ini
add current UI colors as scheme "Meadows"
=> MeadowsSchemePatch

Driver/Font/TrueType/FreeType/ttapi.c
=> Rendering of space in region fixed.

Driver/Font/TrueType/Adapter/ttadapter.h, Driver/Font/TrueType/Adapter/ttwidths.c, Driver/Font/TrueType/Adapter/ttwidths.h, Driver/Font/TrueType/Main/truetypeWidths.asm
Handling of the document zoom reworked.
fixes #828
=> 828 ttf driver skew does not work properly with document zoom

Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error1.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error10.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error11.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error12.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error13.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error14.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error15.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error16.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error18.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error19.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error2.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error20.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error3.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error4.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error5.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error7.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error8.htm, Tools/build/product/bbxensem/Trans/Privdata/german/htmlerr/error9.htm
Updated german htmlerror from Achim.
=> Updated german htmlerror from Achim

Library/Pref/ConfigUI/configui.rev, Library/Pref/PrefPntC/Prefpntc.rev, Library/Pref/Prefbg/prefbg.rev, Library/Pref/Prefcomp/prefcomp.rev, Library/Pref/Preffont/preffont.rev, Library/Pref/Prefint/prefint.rev, Library/Pref/Prefintl/prefintl.rev, Library/Pref/Prefkbd/prefkbd.rev, Library/Pref/Preflf/preflf.rev, Library/Pref/Preflo/preflo.rev, Library/Pref/Prefmous/prefmous.rev, Library/Pref/Prefos/prefos.rev, Library/Pref/Prefsndn/prefsndn.rev, Library/Pref/Preftd/preftd.rev, Library/Pref/Prefts/prefts.rev, Library/Pref/Prefvid/prefvid.rev
Revision change for Settingslibraries -> Icons update.
=> Revision change

Library/Pref/PrefPntC/Prefpntc.rev, Library/Pref/PrefPntC/prefpntc.rev, Library/Pref/Prefsnd/prefsnd.rev, Library/Pref/Prefsndn/prefsndn.rev
=> Revision update 2

Installed/Library/FMTools/CvtTool/Makefile, Installed/Library/FMTools/CvtTool/dependencies.mk, Installed/Makefile, Tools/build/product/bbxensem/bbxensem.filetree
=> add "Convert 1.x Document" File Manager plugin to build

Library/Convert/convert.gp, Tools/build/product/bbxensem/bbxensem.filetree
It should have been part of PR #857 but wasn't.
=> add convert.geo to build

Driver/Font/TrueType/Adapter/ttwidths.c
=> Handling aspect correction fixed.

Driver/Font/TrueType/Adapter/ttpath.c, Driver/Font/TrueType/Adapter/ttwidths.c
- calculation of the transformation matrix for Gen_In_Region corrected
- minor optimizations
fixes #963
=> Ttf driver skew does not work properly after paste inside
